package dcbb.core.content

import dcbb.core.budget.Budget
import dcbb.core.model.Amount
import dcbb.core.model.CardDef
import dcbb.core.model.CardType
import dcbb.core.model.ConstantSpec
import dcbb.core.model.Effect
import dcbb.core.model.Face
import dcbb.core.model.StatusType
import kotlin.math.abs

/**
 * Card variants a run creates (docs/05, docs/08). They are ordinary card definitions with a suffixed id, so the
 * combat engine plays them like any other card:
 *
 * - **Inscribed** (`id+`): the upgrade from Still Points and the Antiquarian. Budget ×1.30 of the card's target.
 *   Authored when a card provides one; otherwise generated by raising the card's numbers one step at a time toward
 *   that budget, and checked against it like every other card.
 * - **Misprinted** (`id~`): a card the Weave rewrote during an out-of-combat Unravel. It rolls a generic Misprint face
 *   for its type and cost each time it is drawn (docs/08 "Misprint Tables").
 */
object Variants {
    const val INSCRIBED = "+"
    const val MISPRINTED = "~"
    const val INSCRIBED_BUDGET = 1.30

    fun inscribedId(id: String) = baseId(id) + INSCRIBED
    fun misprintedId(id: String) = baseId(id) + MISPRINTED
    fun baseId(id: String) = id.removeSuffix(INSCRIBED).removeSuffix(MISPRINTED)
    fun isInscribed(id: String) = id.endsWith(INSCRIBED)
    fun isMisprinted(id: String) = id.endsWith(MISPRINTED)

    /** The budget an Inscribed version aims for: ×1.30 of the base card's target. */
    fun inscribedTarget(base: CardDef) = Budget.target(base) * INSCRIBED_BUDGET

    /** [tweak] adjusts the generated upgrade when a card needs an authored one (it only changes what differs). */
    fun inscribe(base: CardDef, tweak: ((CardDef) -> CardDef)? = null): CardDef {
        val generated = raise(base)
        val upgraded = tweak?.invoke(generated) ?: generated
        return upgraded.copy(id = inscribedId(base.id), name = base.name + INSCRIBED)
    }

    /** Null for cards with no Misprint table (Constants, Hazards). */
    fun misprint(base: CardDef, tables: (CardType, Int) -> List<Face>?): CardDef? {
        if (base.type == CardType.CONSTANT || base.type == CardType.HAZARD || base.unplayable) return null
        val type = base.forkFaces?.first()?.type ?: base.type
        val faces = tables(type, base.cost.total) ?: return null
        return base.copy(
            id = misprintedId(base.id),
            name = "${base.name} (Misprinted)",
            effects = emptyList(),
            forkFaces = null,
            misprintFaces = faces,
            flavor = "The Weave rewrote this one.",
        )
    }

    // ---- generated upgrades ---------------------------------------------------------------------------------

    /**
     * Greedy: try raising each number by one step and keep the change that brings the card closest to ×1.30 of its
     * target, until no single step helps. Damage and Block can rise repeatedly; counts (Draw, Foresee, Plate, …) at
     * most once, so upgrades stay readable.
     */
    private fun raise(base: CardDef): CardDef {
        val goal = inscribedTarget(base)
        var cur = base
        val used = mutableSetOf<Int>()
        repeat(MAX_STEPS) {
            val dist = abs(Budget.points(cur) - goal)
            var best: CardDef? = null
            var bestKnob = -1
            var bestDist = dist
            for (k in 0 until knobs(cur)) {
                val cand = bump(cur, k) ?: continue
                if (cand.second && k in used) continue
                val d = abs(Budget.points(cand.first) - goal)
                if (d < bestDist - 1e-9) {
                    best = cand.first
                    bestKnob = k
                    bestDist = d
                }
            }
            if (best == null) return cur
            cur = best
            used += bestKnob
        }
        return cur
    }

    private const val MAX_STEPS = 12

    private fun knobs(def: CardDef): Int = Knobs(-1).also { it.walk(def) }.count

    /** The card with knob [k] raised one step, and whether that knob is a count (raised at most once). */
    private fun bump(def: CardDef, k: Int): Pair<CardDef, Boolean>? {
        val w = Knobs(k)
        val out = w.walk(def)
        return if (w.hit) out to w.countKnob else null
    }

    /** Walks every raisable number in a card; when the running index reaches [target], that number is raised. */
    private class Knobs(val target: Int) {
        var count = 0
        var hit = false
        var countKnob = false

        private fun here(isCount: Boolean): Boolean {
            val mine = count++ == target
            if (mine) {
                hit = true
                countKnob = isCount
            }
            return mine
        }

        fun walk(def: CardDef): CardDef = def.copy(
            effects = effects(def.effects),
            forkFaces = def.forkFaces?.map { Face(it.type, effects(it.effects)) },
            misprintFaces = def.misprintFaces?.map { Face(it.type, effects(it.effects)) },
            constant = def.constant?.let { constant(it) },
        )

        private fun constant(c: ConstantSpec): ConstantSpec {
            val strikeDamage = if (here(false) && c.strikeDamage > 0) c.strikeDamage + 1 else c.strikeDamage
            val strikeBlock = if (here(false) && c.strikeBlock > 0) c.strikeBlock + 1 else c.strikeBlock
            return c.copy(dawn = effects(c.dawn), dusk = effects(c.dusk), strikeDamage = strikeDamage, strikeBlock = strikeBlock)
        }

        private fun effects(list: List<Effect>): List<Effect> = list.map { effect(it) }

        // Every slot counts as a knob even when it can't move, so knob indices stay stable while numbers change.
        private fun amount(a: Amount): Amount = if (here(false) && a.base > 0) a.copy(base = a.base + 1) else a

        private fun effect(e: Effect): Effect = when (e) {
            is Effect.Damage -> e.copy(amount = amount(e.amount))
            is Effect.Block -> e.copy(amount = amount(e.amount))
            is Effect.GainPlate -> if (here(true)) e.copy(n = e.n + 1) else e
            is Effect.ApplyStatus -> if (e.status != StatusType.SLOW && here(true)) e.copy(n = e.n + 1) else e
            is Effect.Draw -> if (here(true)) e.copy(n = e.n + 1) else e
            is Effect.Foresee -> if (here(true)) e.copy(n = e.n + 1) else e
            is Effect.Recall -> if (here(true)) e.copy(n = e.n + 1) else e
            is Effect.Shift -> if (here(true)) e.copy(n = e.n + 1) else e
            is Effect.BleedThrough -> if (here(true)) e.copy(n = e.n + 1) else e
            is Effect.RestoreLastPhaseLoss -> if (here(true)) e.copy(max = e.max + 4) else e
            is Effect.GainParadox -> if (here(true) && e.n > 0) e.copy(n = e.n - 1) else e
            is Effect.When -> e.copy(then = effects(e.then), otherwise = effects(e.otherwise))
            is Effect.Schedule -> e.copy(effects = effects(e.effects))
            else -> e
        }
    }
}
