package dcbb.sim

import dcbb.core.bot.RunBot
import dcbb.core.bot.RunRunner
import dcbb.core.content.FirstHour
import dcbb.core.run.MomentType
import dcbb.core.run.RunEngine
import dcbb.core.run.RunReplay
import dcbb.core.run.RunState
import dcbb.core.run.Screen
import java.io.File
import java.util.concurrent.Callable
import java.util.concurrent.Executors

/**
 * Run-level simulation (docs/09 "Testing and QA"): whole runs of The First Hour's Act I played by [RunBot] (the planner
 * in fights, heuristics between them), many seeds per operative. Deterministic for a given seed count.
 *
 * Usage: sim --runs N [--threads N] [--out FILE]
 *        sim --replay "r1 vowknight 1234 london_1843 c0 P/12//// ..."   (a run code copied from the web client)
 */
fun runSim(opts: Map<String, String>) {
    val runs = opts["runs"]!!.toInt()
    val threads = opts["threads"]?.toInt() ?: Runtime.getRuntime().availableProcessors()
    val re = RunEngine(FirstHour.run)
    val ops = re.content.operatives.keys.sorted()
    val started = System.nanoTime()
    val pool = Executors.newFixedThreadPool(threads)
    val results = try {
        val jobs = ops.flatMap { op -> (1..runs).map { i -> Callable { op to RunRunner.play(re, op, runSeed(op, i), RunBot(runSeed(op, i))).first } } }
        pool.invokeAll(jobs).map { it.get() }
    } finally {
        pool.shutdown()
    }
    val seconds = (System.nanoTime() - started) / 1e9
    val report = RunReport(re, results.groupBy({ it.first }, { it.second }), runs).render()
    val out = opts["out"]
    if (out != null) {
        File(out).absoluteFile.parentFile.mkdirs()
        File(out).writeText(report)
        println("Wrote $out (${results.size} runs in ${"%.1f".format(seconds)} s on $threads threads)")
    } else {
        println(report)
        System.err.println("${results.size} runs in ${"%.1f".format(seconds)} s on $threads threads")
    }
}

/** Plays run [index] of [op] as `--runs` would, then prints its replay code and full log: `--run-trace op/index`. */
fun traceRun(spec: String) {
    val (op, index) = spec.split("/")
    val re = RunEngine(FirstHour.run)
    val seed = runSeed(op, index.toInt())
    val (_, actions) = RunRunner.play(re, op, seed, RunBot(seed))
    val code = RunReplay(op, seed, re.rc.eras.first().id, actions).encode()
    println("Replay: $code")
    replayRun(code)
}

/** Replays a run code and prints its log. */
fun replayRun(code: String) {
    val re = RunEngine(FirstHour.run)
    val r = RunReplay.parse(code.substringAfter("Replay:").trim())
    var out = re.start(r.operative, r.seed, r.era)
    out.log.forEach { println(it) }
    for ((i, a) in r.actions.withIndex()) {
        val next = re.apply(out.state, a)
        if (next.error != null) {
            println("Action ${i + 1} (${RunReplay.encode(a)}) was rejected: ${next.error}")
            return
        }
        next.log.forEach { println(it) }
        next.events.forEach { println("  " + it.text) }
        out = next
    }
    val s = out.state
    println("State: ${s.screen::class.simpleName}, step ${s.step}, HP ${s.hp}/${s.maxHp}, Hours ${s.hours}, Paradox ${s.paradox}, deck ${s.deck.size}")
}

private fun runSeed(op: String, i: Int): Long {
    var h = 1469598103934665603L
    for (ch in "run/$op") h = (h xor ch.code.toLong()) * 1099511628211L
    return (h and 0x7fffffffffffL) + i
}

private class RunReport(val re: RunEngine, val byOp: Map<String, List<RunState>>, val runs: Int) {
    private val content = re.content
    private fun pct(x: Double) = if (x.isNaN()) "–" else "%.0f%%".format(100 * x)
    private fun num(x: Double, d: Int = 1) = if (x.isNaN()) "–" else "%.${d}f".format(x)
    private fun List<Double>.avg() = if (isEmpty()) Double.NaN else average()
    private fun name(op: String) = content.operative(op).name

    fun render(): String = buildString {
        val total = byOp.values.sumOf { it.size }
        appendLine("# Run simulation: The First Hour, Act I")
        appendLine()
        appendLine("$total runs ($runs per operative), played by the run bot: the planner in every fight, simple heuristics")
        appendLine("between fights (it never Glimpses and spends Foresight only to look at Elites). Generated by")
        appendLine("`./gradlew :sim:run --args=\"--runs $runs --out reports/run-latest.md\"`. Deterministic: rerunning gives the same report.")
        appendLine()

        appendLine("## Outcomes")
        appendLine()
        appendLine("| Operative | Act I cleared | Reached the boss | Boss win rate | HP entering the boss | Paradox entering the boss | Boss HP lost (wins) | Died before the boss |")
        appendLine("|---|---|---|---|---|---|---|---|")
        for ((op, states) in byOp) {
            val won = states.count { (it.screen as? Screen.Over)?.won == true }
            val bossFights = states.mapNotNull { s -> s.stats.fightRecords.firstOrNull { it.type == MomentType.BOSS } }
            val bossWins = bossFights.filter { it.won }
            appendLine(
                "| ${name(op)} | ${pct(won.toDouble() / states.size)} | ${pct(bossFights.size.toDouble() / states.size)} | " +
                    "${pct(if (bossFights.isEmpty()) Double.NaN else bossWins.size.toDouble() / bossFights.size)} | " +
                    "${pct(bossFights.map { it.hpBefore.toDouble() / it.maxHp }.avg())} | " +
                    "${num(bossFights.map { it.paradoxBefore.toDouble() }.avg())} | " +
                    "${pct(bossWins.map { (it.hpBefore - it.hpAfter).toDouble() / it.maxHp }.avg())} | " +
                    "${pct((states.size - bossFights.size).toDouble() / states.size)} |",
            )
        }
        appendLine()

        appendLine("## What the runs looked like")
        appendLine()
        appendLine("Averages per run.")
        appendLine()
        appendLine("| Operative | Fights | Elites | Cards taken | Skipped | Erased | Inscribed | Deck at the end | Hours earned | Hours spent | Artifacts | Foresight spent | Paradox peak |")
        appendLine("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for ((op, states) in byOp) {
            fun a(f: (RunState) -> Number) = num(states.map { f(it).toDouble() }.avg())
            appendLine(
                "| ${name(op)} | ${a { it.stats.fights }} | ${a { it.stats.elites }} | ${a { it.stats.cardsTaken }} | ${a { it.stats.skipped }} | " +
                    "${a { it.stats.erased }} | ${a { it.stats.inscribed }} | ${a { it.deck.size }} | ${a { it.stats.hoursEarned }} | " +
                    "${a { it.stats.hoursSpent }} | ${a { it.artifacts.size }} | ${a { it.stats.foresightSpent }} | ${a { it.stats.paradoxPeak }} |",
            )
        }
        appendLine()

        appendLine("## Time travel")
        appendLine()
        appendLine("Returning Moments and Rewinds. The bot always Rewinds when it falls with its Anchor unspent, never otherwise.")
        appendLine()
        appendLine("| Operative | Returns dealt | Returns taken | Runs that Rewound | Cleared after a Rewind | Echoes fought | Anchor moves |")
        appendLine("|---|---|---|---|---|---|---|")
        for ((op, states) in byOp) {
            fun a(f: (RunState) -> Number) = num(states.map { f(it).toDouble() }.avg())
            val rewound = states.filter { it.stats.rewinds > 0 }
            val saved = rewound.count { (it.screen as? Screen.Over)?.won == true }
            appendLine(
                "| ${name(op)} | ${a { it.stats.returnsDealt }} | ${a { it.stats.returnsTaken }} | ${pct(rewound.size.toDouble() / states.size)} | " +
                    "${if (rewound.isEmpty()) "–" else "$saved of ${rewound.size}"} | ${a { it.stats.echoesFought }} | ${a { it.stats.anchorMoves }} |",
            )
        }
        appendLine()

        appendLine("## Moments chosen")
        appendLine()
        val types = MomentType.entries.filter { it != MomentType.BOSS }
        appendLine("| Operative | " + types.joinToString(" | ") { it.label } + " |")
        appendLine("|---|" + types.joinToString("") { "---|" })
        for ((op, states) in byOp) {
            appendLine("| ${name(op)} | " + types.joinToString(" | ") { t -> num(states.map { (it.stats.chosen[t] ?: 0).toDouble() }.avg()) } + " |")
        }
        appendLine()

        appendLine("## Fights by kind")
        appendLine()
        appendLine("Share of max HP lost per fight, and how often that kind of fight ended the run.")
        appendLine()
        appendLine("| Operative | Threat 1 | Threat 2 | Threat 3 | Elite | Boss | Unravels per fight |")
        appendLine("|---|---|---|---|---|---|---|")
        for ((op, states) in byOp) {
            val records = states.flatMap { it.stats.fightRecords }
            fun cell(sel: (dcbb.core.run.FightRecord) -> Boolean): String {
                val rs = records.filter(sel)
                if (rs.isEmpty()) return "–"
                val lost = rs.map { (it.hpBefore - it.hpAfter).toDouble() / it.maxHp }.avg()
                val deaths = rs.count { !it.won }
                return "${pct(lost)} · ${rs.size} fights" + if (deaths > 0) " · $deaths deaths" else ""
            }
            appendLine(
                "| ${name(op)} | ${cell { it.type == MomentType.COMBAT && it.threat == 1 }} | ${cell { it.type == MomentType.COMBAT && it.threat == 2 }} | " +
                    "${cell { it.type == MomentType.COMBAT && it.threat == 3 }} | ${cell { it.type == MomentType.ELITE }} | ${cell { it.type == MomentType.BOSS }} | " +
                    "${num(records.map { it.unravels.toDouble() }.avg(), 2)} |",
            )
        }
        appendLine()

        appendLine("## Encounters")
        appendLine()
        appendLine("All operatives together: fights, average share of max HP lost, and deaths.")
        appendLine()
        appendLine("| Encounter | Fights | HP lost | Deaths |")
        appendLine("|---|---|---|---|")
        val all = byOp.values.flatten().flatMap { it.stats.fightRecords }
        for ((enc, rs) in all.groupBy { it.encounter }.toList().sortedByDescending { it.second.size }) {
            appendLine(
                "| ${content.encounter(enc).name} | ${rs.size} | ${pct(rs.map { (it.hpBefore - it.hpAfter).toDouble() / it.maxHp }.avg())} | " +
                    "${rs.count { !it.won }} |",
            )
        }
    }
}
